/*
 * SYSTICK_Config.h
 *
 *  Created on: Dec 16, 2021
 *      Author: Abdelrhman Badr
 */

#ifndef SYSTICK_CONFIG_H_
#define SYSTICK_CONFIG_H_

/*
 * SYSTICK_AHB_CLK
 * SYSTICK_AHB_CLK_OVER_8
 */
#define SYSTICK_CLOCK		(SYSTICK_AHB_CLK_OVER_8)

/*
 * SYSTICK_ENABLE_INTERRUPT
 * SYSTICK_DISABLE_INTERRUPT
 */
#define SYSTICK_INTERRUPT	(SYSTICK_ENABLE_INTERRUPT)

#endif /* SYSTICK_CONFIG_H_ */
